### ISSUE TITLE
Add potential XRP / JPY exchanges and address

### ISSUE THREAD

**Issue by LLAC3** [mouradski/xrapid_alert#25]
**JAPAN Japanese Yen XRP/JPY |   |   |   |**  
-- | -- | -- | -- | --
LIQUID ( RATE A ) XRP/JPY 
rHQ6kEtVUPk6mK9XKnjRoudenoHzJ8ZL9p
rMbWmirwEtRr7pNmhN4d4ysTMBvBxdvovs
  |   |   |   |  
SBIVC |  ( Already done ) 
  |   |   |   |  
Bitbank | ( Sur le site de ripple pour XRP/JPY) |   |   | ( Rate B ) 
  | rLbKbPyuvs4wc1h13BEPHgbFGsRXMeFGL6 |   |   |  
  | rw7m3CtVHwGSdhFjV4MyJozmZJv3DYQnsA |   |   |  
  | rwggnsfxvCmDb3YP9Hs1TaGvrPR7ngrn7Z |   |   |  
  |   |   |   |  
Coincheck ( Sur le site de Ripple pour XRP/JPY ) |   |   |   |  
  |   |   |   |  
  | rNQEMJA4PsoSrZRn9J6RajAYhcDzzhf8ok |   |   |  
  | rwgvfze315jjAAxT2TyyDqAPzL68HpAp6v |   |   |  
  |   |   |   |  
  |   |   |   |  

Coinfield : | ( Sur le site de ripple pour XRP/JPY) |   |   |  
  | rK7D3QnTrYdkp1fGKKzHFNXZpqN8dUCfaf |   |   |  ( Already done )

**Comment by mouradski** [comment]
t'es sûr pour coinchek ? 

la paire XRP/JPY n'est pas reconnue par l'api
https://coincheck.com/api/trades?pair=xrp_jpy

alors que celle de BTC est bien reconnue 

https://coincheck.com/api/trades?pair=btc_jpy

**Comment by mouradski** [comment]
Lquid , Bitbank, Coinfield ajoutés pour la pair XRP/JPY (Adresses et API) 

Coincheck impossible car le market XRP n'est pas encore public (ouvrir un ticket à part)

SBIVC, en attente des bonnes adresses (je propose qu'on ouvre un ticket à part)

https://github.com/mouradski/xrapid_alert/commit/dc6deb62a3f0d40f4eb7b77a917768676a1f8b9e
