### ISSUE TITLE
Add potential exchanges XRP/KRW  ( South Korea )

### ISSUE THREAD

**Issue by LLAC3** [mouradski/xrapid_alert#26]
UpBit | ( RATE B   et sur le site de ripple pour XRP/KRW) |   |   |   |  
-- | -- | -- | -- | -- | --
  | rNzT5xopUaJK8L7mHbThUGKaHoct62dNBC |   |   |   |  
  | rN9qNpgnBaZwqCg8CvUZRPqCcPPY7wfWep |   |   |   |  
  | rJYQKfsTi8XCLZ1vGSf9CxiL4prz5bvbtz |   |   |   |  
  | rBszWJzYpNoqoY4xKuGUpN23b6EBT41ocF |   |   |   |  
  |   |   |   |   |  
Bithumb | RATE  C Sur le site de ripple pour XRP/KRW) |   |   |   |  
  | rPMM1dRp7taeRkbT74Smx2a25kTAHdr4N5 |   |   |   |  
  | rNTkgxs5WG5mU5Sz26YoDVrHim5Y5ohC7 |   |   |   |  
  | r9hUMZBc3MWRc4YdsdZgNCW5Qef8wNSXpb |   |   |   |  
  | r9LHiNDZvpLoWPoKnbH2JWjFET8zoYT4Y5 |   |   |   |  
  | rBF3GWchod3QL8TEYicwSeMu6sjXqKFaQ2 |   |   |   |  
  | rDFCAUDVB5QhB61ETGT6tf8Rm1zBsj8LHU |   |   |   |  
  | rsdd66csGZkTzk42NDpJun7PNrGsC7WJHv |   |   |   |  
  |   |   |   |   |  
Coinone | RATE B  Sur le site de ripple pour XRP/KRW) |   |   |   |  
  | rp2diYfVtpbgEMyaoWnuaWgFCAkqCAEg28 |   |   |   |  
  | rPsmHDMkheWZvbAkTA8A9bVnUdadPn7XBK |   |   |   |

**Comment by mouradski** [comment]
Du coup le quel prioriser ? Rate B c'est bon signe ou pas ? :D

**Comment by LLAC3** [comment]
Ils sont dans l'ordre. UpBit en prem's ;-)
