### ISSUE TITLE
Add Ukraine Fiat Exchange XRP/UAH

### ISSUE THREAD

**Issue by LLAC3** [mouradski/xrapid_alert#30]
Ukraine XRP/UAH |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
  |   |   |   |   |   |  
EXMO | rUocf1ixKzTuEe34kmVhRvGqNCofY1NJzV |   |   |   | https://exmo.com/ |  
  | rUCjhpLHCcuwL1oyQfzPVeWHsjZHaZS6t2 |   |   |   |   |  
  | rsTv5cJK2EMJhYqUUni4sYBonVk7KqTxZg |   |   |   |   |  
  | rLJPjRYGDVVEjv4VrJtouzqzyJ51YtdZKY |   |   |   |   |  
  |   |   |   |   |   |  
Kuna | rMtb2JEX8xmcgSKxCB7aZPDyzyVhbM2RzV |   |   |   | https://kuna.io/ |  
  |   |   |   |   |   |  
  |   |   |   |   |   |  
BTC TRADE UA |   | rpd6t1Z7o4ME2jgzhfBjYUwhpEcBnZufGG |   |   | https://btc-trade.com.ua/ |  
  |   |   |   |   |   |

**Comment by mouradski** [comment]
https://github.com/mouradski/xrapid_alert/commit/1a5ad0d45c73b9c26332281045472dc4c918591d
