### ISSUE TITLE
Add SBI VC TRADE New address 

### ISSUE THREAD

**Issue by LLAC3** [mouradski/xrapid_alert#37]
SBI VC TRADE (1) 
rDDyH5nfvozKZQCwiBrWfcE528sWsBPWET

SBI VC TRADE (2)
rKcVYzVK1f4PhRFjLhWP7QmteG5FpPgRub

**Comment by mouradski** [comment]
https://github.com/mouradski/xrapid_alert/commit/b30f45845c76cf80e9cb0ceb71e2fa847eb139e3
