### ISSUE TITLE
Daily Volume ATH value is incorrect

### ISSUE THREAD

**Issue by RetirePerspired** [mouradski/xrapid_alert#42]
This call |https://github.com/mouradski/xrapid_alert/blob/6f2d121d1475ba2025375f156eaa0020b41399f1/src/main/java/space/xrapid/service/ExchangeToExchangePaymentService.java#L106

is pulling an incorrect number because this method - https://github.com/mouradski/xrapid_alert/blob/6f2d121d1475ba2025375f156eaa0020b41399f1/src/main/java/space/xrapid/service/ExchangeToExchangePaymentService.java#L124

is only pulling values from the last 22 days. 

Solution - ATH value should pull from all available days, not just the past 22. I noticed this because the ATH value should be ~$16 million and right now it's showing as ~$13 million.

**Comment by mouradski** [comment]
Thanks, hotfix https://github.com/mouradski/xrapid_alert/commit/6a29a3ed195129cf427eacb4ad97fba196e6a410

we'll change the way we calculate ATHs using only SQL in a future commit
