### ISSUE TITLE
ODL Map 3hrs summary in reverse order

### ISSUE THREAD

**Issue by shortthefomo** [mouradski/xrapid_alert#55]
The transactions of the last 3hrs need to be shown in reverse order? Right now when you view them you see the latest to the oldest. Makes more logical sense to show them the other way around.

**Comment by mouradski** [comment]
thanks :) 

fixed https://github.com/mouradski/xrapid_alert/commit/048996aecbd4bb40c1a9be427c8d30b952fa7a49
