### ISSUE TITLE
Luno exchange has further pairs not covered

### ISSUE THREAD

**Issue by shortthefomo** [mouradski/xrapid_alert#65]
NGN:  Nigerian Naira 
https://api.luno.com/api/1/trades?pair=XRPNGN

MYR: Malaysian Ringgit
https://api.luno.com/api/1/trades?pair=XRPMYR

Should be rather simple to extend the Luno base you have.

**Comment by mouradski** [comment]
Thank you 👌

https://github.com/mouradski/xrapid_alert/commit/f5554b754005462f81f25f5ff5b2f75a2bc3496a
