### ISSUE TITLE
Indodax 

### ISSUE THREAD

**Issue by shortthefomo** [mouradski/xrapid_alert#73]
Missing the JPY,SGD,USD and EUR pairs they have

https://api.liquid.com/executions?product_id=85&limit=200&page=1 (EUR)
https://api.liquid.com/executions?product_id=83&limit=200&page=1 (JYP)
https://api.liquid.com/executions?product_id=86&limit=200&page=1  (SGD)
https://api.liquid.com/executions?product_id=84&limit=200&page=1 (USD)

**Comment by mouradski** [comment]
Thank you 🙏

SGD already implemented :)
