### ISSUE TITLE
Independentreserve

### ISSUE THREAD

**Issue by shortthefomo** [mouradski/xrapid_alert#74]
You missed the following pairs

SGD - singapore dollar
https://api.independentreserve.com/Public/GetRecentTrades?primaryCurrencyCode=xrp&secondaryCurrencyCode=sgd&numberOfRecentTradesToRetrieve=50

USD
https://api.independentreserve.com/Public/GetRecentTrades?primaryCurrencyCode=xrp&secondaryCurrencyCode=usd&numberOfRecentTradesToRetrieve=50

**Comment by mouradski** [comment]
https://github.com/mouradski/xrapid_alert/commit/8a04b18773a591828f9a016413175d04f3b8dcf7
